language: php

php:
    - 5.6
    - 7

script:
    - composer install --prefer-dist --ignore-platform-reqs
    - vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
    - vendor/bin/php-cs-fixer fix -v --fixers=-empty_return --diff --dry-run ./src
    - vendor/bin/php-cs-fixer fix -v --fixers=-empty_return --diff --dry-run ./test

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
